// <auto-generated />
namespace CRUD_With_CF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class checkbox : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(checkbox));
        
        string IMigrationMetadata.Id
        {
            get { return "201503180833041_checkbox"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
